[package]
name = "solcrypt"
version = "0.2.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = [ "multipart" ] }
tar = "0.4"
tokio = { version = "1.38.0", features = [ "full" ] }
walkdir = "2.5.0"
xz2 = "0.1"


[profile.release]
strip = true
lto = true
opt-level = "s"
