[package]
name = "solcrypt"
version = "0.2.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = [ "blocking", "multipart" ] }
tar = "0.4"
xz2 = "0.1"


[profile.release]
strip = true
lto = true
opt-level = 3
