[package]
name = "solcrypt"
version = "0.2.0"
edition = "2021"

[dependencies]
dirs = "5.0.1"
reqwest = { version = "0.12.5", features = [ "blocking" ] }
walkdir = "2.5.0"

[profile.release]
strip = true
lto = true
opt-level = 3
