[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
actix-multipart = "0.4"
tokio = { version = "1", features = ["full"] }
futures-util = "0.3"
sanitize-filename = "0.5"

